# AgentCore Runtime Configuration
# https://docs.aws.amazon.com/bedrock-agentcore/latest/devguide/runtime-get-started-toolkit.html

default_agent: multimodal

agents:
  multimodal:
    name: rd-knowledge-multimodal-agent
    description: AWS Nova を活用したマルチモーダル AI エージェント
    
    # Entry Point (module:attribute format)
    entrypoint: main:app
    
    # Runtime Configuration
    timeout: 300
    memory_size: 2048
    
    # Model Provider (bedrock for AWS credentials)
    model_provider: bedrock
    
    # Request Header Allowlist
    request_header_allowlist:
      - "X-Amzn-Bedrock-AgentCore-Runtime-Custom-UserId"
      - "X-Amzn-Bedrock-AgentCore-Runtime-Custom-SessionId"

# Environment Variables
environment:
  AWS_REGION: ap-northeast-1
  MODEL_ID: amazon.nova-pro-v1:0
  USE_AGENTCORE_MEMORY: "true"
  OUTPUT_BUCKET: rd-knowledge-multimodal-output
  LOG_LEVEL: INFO

# Tags
tags:
  Project: rd-knowledge-sample
  Environment: dev
  ManagedBy: agentcore-toolkit
